survivor_perks = [
    "A Place For Us",
    "Ace in the Hole",
    "Adrenaline",
    "Aftercare",
    "Alert",
    "Any Means Necessary",
    "Apocalyptic Ingenuity",
    "Appraisal",
    "Autodidact",
    "Babysitter",
    "Background Player",
    "Bada Bada Boom",
    "Balanced Landing",
    "Bardic Inspiration",
    "Better Than New",
    "Better Together",
    "Bite the Bullet",
    "Blast Mine",
    "Blood Pact",
    "Blood Rush",
    "Boil Over",
    "Bond",
    "Boon: Circle of Healing",
    "Boon: Dark Theory",
    "Boon: Exponential",
    "Boon: Illumination",
    "Boon: Shadow Step",
    "Borrowed Time",
    "Botany Knowledge",
    "Bound by Obsession",
    "Breakdown",
    "Breakout",
    "Buckle Up",
    "Built to Last",
    "Calm Spirit",
    "Camaraderie",
    "Champion of Light",
    "Change of Plan",
    "Chemical Trap",
    "Clairvoyance",
    "Clean Break",
    "Come and Get Me!",
    "Conviction",
    "Corrective Action",
    "Counterforce",
    "Cut Loose",
    "Dance With Me",
    "Dark Sense",
    "Dead Hard",
    "Deadline",
    "Deception",
    "Deliverance",
    "Desperate Measures",
    "Detective's Hunch",
    "Distortion",
    "Diversion",
    "Do No Harm",
    "Down to the Last",
    "Dramaturgy",
    "Duty of Care",
    "Déjà Vu",
    "Empathic Connection",
    "Empathy",
    "Extrasensory Perception",
    "Exultation",
    "Eyes of Belmont",
    "Fast Track",
    "Finesse",
    "Five Moves Ahead",
    "Fixated",
    "Flashbang",
    "Flip-Flop",
    "Flow State",
    "Fogwise",
    "For the People",
    "Friendly Competition",
    "Ghost Notes",
    "Hardened",
    "Head On",
    "Hope",
    "Hyperfocus",
    "Inner Focus",
    "Inner Strength",
    "Invocation: Treacherous Crows",
    "Invocation: Weaving Spiders",
    "Iron Will",
    "Kindred",
    "Last Stand",
    "Leader",
    "Left Behind",
    "Light-Footed",
    "Lightweight",
    "Lithe",
    "Low Profile",
    "Lucky Break",
    "Lucky Star",
    "Made for This",
    "Mettle of Man",
    "Mirrored Illusion",
    "Moment of Glory",
    "No Mither",
    "No One Left Behind",
    "Off the Record",
    "ONE-TWO-THREE-FOUR!",
    "Open-Handed",
    "Overcome",
    "Overzealous",
    "Parental Guidance",
    "Pharmacy",
    "Plot Twist",
    "Plunderer's Instinct",
    "Poised",
    "Potential Energy",
    "Power Struggle",
    "Premonition",
    "Prove Thyself",
    "Quick & Quiet",
    "Quick Gambit",
    "Rapid Response",
    "Reactive Healing",
    "Reassurance",
    "Red Herring",
    "Repressed Alliance",
    "Residual Manifest",
    "Resilience",
    "Resurgence",
    "Road Life",
    "Rookie Spirit",
    "Saboteur",
    "Scavenger",
    "Scene Partner",
    "Second Wind",
    "Self-Care",
    "Self-Preservation",
    "Shoulder the Burden",
    "Slippery Meat",
    "Small Game",
    "Smash Hit",
    "Solidarity",
    "Soul Guard",
    "Specialist",
    "Spine Chill",
    "Sprint Burst",
    "Stake Out",
    "Still Sight",
    "Streetwise",
    "Strength in Shadows",
    "Teamwork: Collective Stealth",
    "Teamwork: Full Circuit",
    "Teamwork: Power of Two",
    "Teamwork: Soft-Spoken",
    "Teamwork: Throw Down",
    "Teamwork: Toughen Up",
    "Technician",
    "Tenacity",
    "This Is Not Happening",
    "Troubleshooter",
    "Unbreakable",
    "Up the Ante",
    "Urban Evasion",
    "Vigil",
    "Visionary",
    "Wake Up!",
    "We See You",
    "We'll Make It",
    "We're Gonna Live Forever",
    "Wicked",
    "Will to Live",
    "Windows of Opportunity",
    "Wiretap",
]

killer_perks = [
    "A Nurse's Calling",
    "Agitation",
    "Alien Instinct",
    "All-Shaking Thunder",
    "Awakened Awareness",
    "Bamboozle",
    "Barbecue & Chili",
    "Batteries Included",
    "Beast of Prey",
    "Bitter Murmur",
    "Blood Echo",
    "Blood Warden",
    "Bloodhound",
    "Brutal Strength",
    "Call of Brine",
    "Corrupt Intervention",
    "Coulrophobia",
    "Coup de Grâce",
    "Cruel Limits",
    "Cull the Weak",
    "Dark Arrogance",
    "Dark Devotion",
    "Darkness Revealed",
    "Dead Man's Switch",
    "Deadlock",
    "Deathbound",
    "Deerstalker",
    "Discordance",
    "Dissolution",
    "Distressing",
    "Dominance",
    "Dragon's Grip",
    "Enduring",
    "Eruption",
    "Fire Up",
    "Forced Hesitation",
    "Forced Penance",
    "Forever Entwined",
    "Franklin's Demise",
    "Friends 'Til the End",
    "Furtive Chase",
    "Game Afoot",
    "Gearhead",
    "Genetic Limits",
    "Grim Embrace",
    "Haywire",
    "Help Wanted",
    "Hex: Blood Favor",
    "Hex: Crowd Control",
    "Hex: Devour Hope",
    "Hex: Face the Darkness",
    "Hex: Haunted Ground",
    "Hex: Hive Mind",
    "Hex: Huntress Lullaby",
    "Hex: No One Escapes Death",
    "Hex: Nothing But Misery",
    "Hex: Overture of Doom",
    "Hex: Pentimento",
    "Hex: Plaything",
    "Hex: Retribution",
    "Hex: Ruin",
    "Hex: The Third Seal",
    "Hex: Thrill of the Hunt",
    "Hex: Two Can Play",
    "Hex: Undying",
    "Hex: Wretched Fate",
    "Hoarder",
    "Hubris",
    "Human Greed",
    "Hysteria",
    "I'm All Ears",
    "Infectious Fright",
    "Insidious",
    "Iron Grasp",
    "Iron Maiden",
    "Keep Them Waiting",
    "Knock Out",
    "Languid Touch",
    "Leverage",
    "Lethal Pursuer",
    "Lightborn",
    "Machine Learning",
    "Mad Grit",
    "Make Your Choice",
    "Merciless Storm",
    "Mindbreaker",
    "Monitor & Abuse",
    "Nemesis",
    "No Quarter",
    "No Way Out",
    "None Are Free",
    "Nowhere to Hide",
    "Oppression",
    "Overcharge",
    "Overwhelming Presence",
    "Phantom Fear",
    "Pop Goes the Weasel",
    "Predator",
    "Rancor",
    "Rapid Brutality",
    "Ravenous",
    "Remember Me",
    "Scourge Hook: Floods of Rage",
    "Scourge Hook: Gift of Pain",
    "Scourge Hook: Hangman's Trick",
    "Scourge Hook: Jagged Compass",
    "Scourge Hook: Monstrous Shrine",
    "Scourge Hook: Pain Resonance",
    "Secret Project",
    "See How They Run",
    "Septic Touch",
    "Shadowborn",
    "Shattered Hope",
    "Sloppy Butcher",
    "Spies from the Shadows",
    "Spirit Fury",
    "Starstruck",
    "Stridor",
    "Superior Anatomy",
    "Surge",
    "Surveillance",
    "Terminus",
    "Territorial Imperative",
    "Thanatophobia",
    "THWACK!",
    "Thrilling Tremors",
    "Tinkerer",
    "Trail of Torment",
    "Turn Back The Clock",
    "Ultimate Weapon",
    "Unbound",
    "Undone",
    "Unforeseen",
    "Unnerving Presence",
    "Unrelenting",
    "Wandering Eye",
    "Weave Attunement",
    "Whispers",
    "Zanshin Tactics",
]

exhaustion_perks = [
    "Adrenaline",
    "Background Player",
    "Balanced Landing",
    "Blood Rush",
    "Dead Hard",
    "Ghost Notes",
    "Head On",
    "Overcome",
    "Rapid Response",
    "Smash Hit",
    "Sprint Burst",
    "Vigil" 
    ]

healing_perks = [
    "Botany Knowledge",
    "For the People",
    "Self-Care",
    "Inner Strength",
    "Resurgence",
    "We'll Make It"
    ]

team_perks = [
    "Aftercare",
    "Any Means Necessary",
    "Babysitter",
    "Bond",
    "Borrowed Time",
    "Breakout",
    "Buckle Up",
    "Desperate Measures",
    "Empathic Connection",
    "Empathy",
    "For the People",
    "Friendly Competition",
    "Kindred",
    "Camaraderie",
    "Leader",
    "We'll Make It",
]

stealth_perks = [
    "Bite the Bullet",
    "Calm Spirit",
    "Dance With Me",
    "Deception",
    "Distortion",
    "Diversion",
    "Iron Will",
    "Light-Footed",
    "Lucky Star",
    "Quick & Quiet",
]

chase_perks = [
    "Background Player",
    "Balanced Landing",
    "Champion of Light",
    "Cut Loose",
    "Dead Hard",
    "Dramaturgy",
    "Lithe",
    "Overcome",
    "Smash Hit",
    "Sprint Burst",
    "Windows of Opportunity",
]

generator_perks = [
    "Blast Mine",
    "Built to Last",
    "Corrective Action",
    "Deadline",
    "Déjà Vu",
    "Fast Track",
    "Fogwise",
    "Hyperfocus",
    "Invocation: Weaving Spiders",
    "Prove Thyself",
    "Stake Out",
]

aura_perks = [
    "Alert",
    "Bond",
    "Bound by Obsession",
    "Clairvoyance",
    "Dark Sense",
    "Detective's Hunch",
    "Empathy",
    "Fogwise",
    "Kindred",
    "Windows of Opportunity",
]

anti_tunnel_perks = [
    "Adrenaline",
    "Boil Over",
    "Breakdown",
    "Buckle Up",
    "Will to Live",
    "Deliverance",
    "Off the Record",
    "Resurgence",
    "Soul Guard",
    "Unbreakable",
]
