survivor_perks = [
    "Ace in the Hole",
    "Adrenaline",
    "Aftercare",
    "Alert",
    "Any Means Necessary",
    "Appraisal",
    "Autodidact",
    "Background Player",
    "Balanced Landing",
    "Better Than New",
    "Bite the Bullet",
    "Blast Mine",
    "Blood Pact",
    "Blood Rush",
    "Boil Over",
    "Bond",
    "Boon: Circle of Healing",
    "Boon: Dark Theory",
    "Boon: Exponential",
    "Boon: Illumination",
    "Boon: Shadow Step",
    "Borrowed Time",
    "Botany Knowledge",
    "Breakdown",
    "Breakout",
    "Buckle Up",
    "Built to Last",
    "Calm Spirit",
    "Champion of Light",
    "Chemical Trap",
    "Clairvoyance",
    "Corrective Action",
    "Counterforce",
    "Cut Loose",
    "Dance With Me",
    "Dark Sense",
    "Dead Hard",
    "Deadline",
    "Deception",
    "Decisive Strike",
    "Deliverance",
    "Desperate Measures",
    "Detective's Hunch",
    "Distortion",
    "Diversion",
    "Dramaturgy",
    "Déjà Vu",
    "Empathic Connection",
    "Empathy",
    "Fast Track",
    "Flashbang",
    "Flip-Flop",
    "Fogwise",
    "For the People",
    "Friendly Competition",
    "Guardian",
    "Head On",
    "Hope",
    "Hyperfocus",
    "Inner Focus",
    "Inner Healing",
    "Invocation: Weaving Spiders",
    "Iron Will",
    "Kindred",
    "Kinship",
    "Leader",
    "Left Behind"
    ]

exhaustion_perks = [
    "Adrenaline",
    "Background Player",
    "Balanced Landing",
    "Blood Rush",
    "Dead Hard",
    "Ghost Notes",
    "Head On",
    "Overcome",
    "Rapid Response",
    "Smash Hit",
    "Sprint Burst",
    "Vigil" 
    ]

healing_perks = [
    "Botany Knowledge",
    "For the People",
    "Self Care",
    "Inner Healing",
    "Resurgence",
    "We'll Make It"
    ]